Improve code

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,13 +10,19 @@ is_executable() {
 
 fetch() {
 	local url="$1"
-	local extra_args=()
+	local extra_args=() status_code=''
 
 	if [ "${GITHUB_API_TOKEN:-}" ]; then
 		extra_args+=(--header "Authorization: token $GITHUB_API_TOKEN")
 	fi
 
-	curl -fLO -C - "${extra_args[@]}" "$url"
+	status_code=$(curl -w "%{http_code}" -fLO -C - "${extra_args[@]}" "$url" || true)
+
+	# 416 means that the file range is already downloaded
+	if [ "$status_code" -ge 400 ] && ! [ "$status_code" = 416 ]; then
+		printf "$ERROR: Failed to download %s (HTTP status code: %s)\n" "$url" "$status_code"
+		return 1
+	fi
 }
 
 fetch_tag_info() {
@@ -79,25 +85,26 @@ If you want to force asfd to manage this version (meaning that \`asdf uninstall\
 }
 
 # Pipe urls in, pipes file prefix out
-find_tarball_name() {
+find_tarball_url() {
 	local version="$1"
 
 	local tarballs="" tarballs_len=0
 	tarballs=$(grep -E '\.tar\.gz$')
-	tarballs_len=$(printf "%s\n" "$tarballs" | wc -l)
+	tarballs_len=$(wc -l <<< "$tarballs")
 
 	if [ "$tarballs_len" = 0 ]; then
 		return 1
 	fi
 
 	if [ "$tarballs_len" = 1 ]; then
-		printf "%s\n" "${tarballs%.tar.gz}"
+		printf "%s\n" "$tarballs"
 		return 0
 	fi
 
 	# Since Proton11 multiple archs are available, we need to find the correct one for the current system
 	local arch='' found_name='' expected_name="$version"
 	arch=$(uname -m)
+	arch=arm64
 
 	case "$arch" in
 		aarch64|arm64)
@@ -105,16 +112,11 @@ find_tarball_name() {
 			;;
 	esac
 
-	found_name=$(printf "%s\n" "$tarballs" | grep "$expected_name.tar.gz" || true)
-
-	if [ "$found_name" ]; then
-		printf "%s\n" "${found_name%.tar.gz}"
-		return 0
-	else
-		printf "%s\n" "$tarballs" | head -n1
-	fi
+	grep "$expected_name.tar.gz" <<< "$tarballs" \
+		|| head -n1 <<< "$tarballs"
 }
 
+# Download is a subshell, so we can cd into the download path without affecting the parent shell
 download() (
 	local download_type="$1" version="$2" download_path="$3"
 	download_path="$(cd "$3" && pwd -P)"
@@ -129,14 +131,13 @@ download() (
 
 	print_changelog <<< "$tag_info"
 
-	local basename='' tarball_url='' checksum_url=''
-	basename="$(printf "%s\n" "$urls" | find_tarball_name "$version" || true)"
-	tarball_url="$basename.tar.gz"
-	checksum_url="$basename.sha512sum"
+	local tarball_url='' checksum_url=''
+	tarball_url="$(find_tarball_url "$version" <<< "$urls" || true)"
+	checksum_url="$(grep "${tarball_url%.tar.gz}.sha512sum" <<< "$urls" || true)"
 
-	if ! printf "%s\n" "$urls" | grep -q "$checksum_url"; then
+	if ! [ "$checksum_url" ]; then
 		printf "$ERROR: No checksum found for version %s; Release is broken or too old\n" "$version"
-		exit 1
+		return 1
 	fi
 
 	if [ "$download_type" = version ]; then
@@ -155,11 +156,11 @@ download() (
 		if ! sha512sum -c ./*.sha512sum; then
 			printf "$ERROR $(colored "$RED" "Checksum verification failed!\n"). Aborting...\n"
 			rm ./*.{tar.gz,sha512sum}
-			exit 1
+			return 1
 		fi
 	else
 		printf "Building from source not supported\n"
-		exit 1
+		return 1
 	fi
 )
 
